# ----------------------------------------------
# Arquitectura Scripting Unix Brqx 2023
# Version Curso 0.0.1
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

# Lista de Scripts - Capitulo 029
# ==============================================
# Nota : Se crea anagrama.x a partir del capitulo 19
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

. ${ARQ_S}exec/tmpdir.x
. ${ARQ_S}exec/colores.x
. ${ARQ_S}exec/fechas.x
. ${ARQ_S}exec/anagrama.x

# ----------------------------------------------
